version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: rapper
    main: ./main.go
    binary: rapper
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -trimpath
      - -tags=netgo
    ldflags:
      - -s -w
      - -X github.com/anibaldeboni/rapper/internal/ui.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64

archives:
  - id: rapper-archive
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true # semantic-release gera o changelog

release:
  github:
    owner: anibaldeboni
    name: rapper
  draft: false
  prerelease: auto
