token: JWT of your application
path:
  method: PUT
  template: https://api.myapp.io/users/{{.id}}
payload:
  template: |
    {
      "address": {
        "street": "{{.street_name}}",
        "number": "{{.house_number}}",
        "city": "{{.city}}"
      }
    }
csv:
  fields:
    - id
    - street_number
    - house_number
    - city
  separator: ','