// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anibaldeboni/rapper/internal/config (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -destination mock/manager_mock.go github.com/anibaldeboni/rapper/internal/config Manager
//

// Package mock_config is a generated GoMock package.
package mock_config

import (
	reflect "reflect"

	config "github.com/anibaldeboni/rapper/internal/config"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockManager) Get() *config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*config.Config)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockManagerMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockManager)(nil).Get))
}

// GetProfileManager mocks base method.
func (m *MockManager) GetProfileManager() config.ProfileManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileManager")
	ret0, _ := ret[0].(config.ProfileManager)
	return ret0
}

// GetProfileManager indicates an expected call of GetProfileManager.
func (mr *MockManagerMockRecorder) GetProfileManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileManager", reflect.TypeOf((*MockManager)(nil).GetProfileManager))
}

// OnChange mocks base method.
func (m *MockManager) OnChange(callback func(*config.Config)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnChange", callback)
}

// OnChange indicates an expected call of OnChange.
func (mr *MockManagerMockRecorder) OnChange(callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChange", reflect.TypeOf((*MockManager)(nil).OnChange), callback)
}

// Save mocks base method.
func (m *MockManager) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockManagerMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockManager)(nil).Save))
}

// Update mocks base method.
func (m *MockManager) Update(cfg *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockManagerMockRecorder) Update(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockManager)(nil).Update), cfg)
}
