// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anibaldeboni/rapper/internal/config (interfaces: ProfileManager)
//
// Generated by this command:
//
//	mockgen -destination mock/profile_mock.go github.com/anibaldeboni/rapper/internal/config ProfileManager
//

// Package mock_config is a generated GoMock package.
package mock_config

import (
	reflect "reflect"

	config "github.com/anibaldeboni/rapper/internal/config"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileManager is a mock of ProfileManager interface.
type MockProfileManager struct {
	ctrl     *gomock.Controller
	recorder *MockProfileManagerMockRecorder
	isgomock struct{}
}

// MockProfileManagerMockRecorder is the mock recorder for MockProfileManager.
type MockProfileManagerMockRecorder struct {
	mock *MockProfileManager
}

// NewMockProfileManager creates a new mock instance.
func NewMockProfileManager(ctrl *gomock.Controller) *MockProfileManager {
	mock := &MockProfileManager{ctrl: ctrl}
	mock.recorder = &MockProfileManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileManager) EXPECT() *MockProfileManagerMockRecorder {
	return m.recorder
}

// Discover mocks base method.
func (m *MockProfileManager) Discover(dir string) ([]config.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Discover", dir)
	ret0, _ := ret[0].([]config.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Discover indicates an expected call of Discover.
func (mr *MockProfileManagerMockRecorder) Discover(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Discover", reflect.TypeOf((*MockProfileManager)(nil).Discover), dir)
}

// GetActive mocks base method.
func (m *MockProfileManager) GetActive() *config.Profile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive")
	ret0, _ := ret[0].(*config.Profile)
	return ret0
}

// GetActive indicates an expected call of GetActive.
func (mr *MockProfileManagerMockRecorder) GetActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockProfileManager)(nil).GetActive))
}

// List mocks base method.
func (m *MockProfileManager) List() []config.Profile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]config.Profile)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockProfileManagerMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProfileManager)(nil).List))
}

// Save mocks base method.
func (m *MockProfileManager) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockProfileManagerMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockProfileManager)(nil).Save))
}

// SetActive mocks base method.
func (m *MockProfileManager) SetActive(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockProfileManagerMockRecorder) SetActive(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockProfileManager)(nil).SetActive), name)
}

// UpdateActive mocks base method.
func (m *MockProfileManager) UpdateActive(cfg *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActive", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActive indicates an expected call of UpdateActive.
func (mr *MockProfileManagerMockRecorder) UpdateActive(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActive", reflect.TypeOf((*MockProfileManager)(nil).UpdateActive), cfg)
}
