// Code generated by mockery v2.40.1. DO NOT EDIT.

package processorMocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Processor is an autogenerated mock type for the Processor type
type Processor struct {
	mock.Mock
}

// Do provides a mock function with given fields: ctx, cancel, filePath
func (_m *Processor) Do(ctx context.Context, cancel func(), filePath string) {
	_m.Called(ctx, cancel, filePath)
}

// NewProcessor creates a new instance of Processor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Processor {
	mock := &Processor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
