// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anibaldeboni/rapper/internal/ui/ports (interfaces: ConfigManager)
//
// Generated by this command:
//
//	mockgen -destination ../mock/config_manager_mock.go -package mock_ui github.com/anibaldeboni/rapper/internal/ui/ports ConfigManager
//

// Package mock_ui is a generated GoMock package.
package mock_ui

import (
	reflect "reflect"

	config "github.com/anibaldeboni/rapper/internal/config"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigManager is a mock of ConfigManager interface.
type MockConfigManager struct {
	ctrl     *gomock.Controller
	recorder *MockConfigManagerMockRecorder
	isgomock struct{}
}

// MockConfigManagerMockRecorder is the mock recorder for MockConfigManager.
type MockConfigManagerMockRecorder struct {
	mock *MockConfigManager
}

// NewMockConfigManager creates a new mock instance.
func NewMockConfigManager(ctrl *gomock.Controller) *MockConfigManager {
	mock := &MockConfigManager{ctrl: ctrl}
	mock.recorder = &MockConfigManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigManager) EXPECT() *MockConfigManagerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConfigManager) Get() *config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*config.Config)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockConfigManagerMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigManager)(nil).Get))
}

// GetActiveProfile mocks base method.
func (m *MockConfigManager) GetActiveProfile() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveProfile")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetActiveProfile indicates an expected call of GetActiveProfile.
func (mr *MockConfigManagerMockRecorder) GetActiveProfile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveProfile", reflect.TypeOf((*MockConfigManager)(nil).GetActiveProfile))
}

// ListProfiles mocks base method.
func (m *MockConfigManager) ListProfiles() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProfiles")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListProfiles indicates an expected call of ListProfiles.
func (mr *MockConfigManagerMockRecorder) ListProfiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProfiles", reflect.TypeOf((*MockConfigManager)(nil).ListProfiles))
}

// Save mocks base method.
func (m *MockConfigManager) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockConfigManagerMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockConfigManager)(nil).Save))
}

// SetActiveProfile mocks base method.
func (m *MockConfigManager) SetActiveProfile(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActiveProfile", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActiveProfile indicates an expected call of SetActiveProfile.
func (mr *MockConfigManagerMockRecorder) SetActiveProfile(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveProfile", reflect.TypeOf((*MockConfigManager)(nil).SetActiveProfile), name)
}

// Update mocks base method.
func (m *MockConfigManager) Update(cfg *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockConfigManagerMockRecorder) Update(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConfigManager)(nil).Update), cfg)
}
