// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anibaldeboni/rapper/internal/ui/ports (interfaces: ConfigProvider)
//
// Generated by this command:
//
//	mockgen -destination ../mock/config_provider_mock.go -package mock_ui github.com/anibaldeboni/rapper/internal/ui/ports ConfigProvider
//

// Package mock_ui is a generated GoMock package.
package mock_ui

import (
	reflect "reflect"

	config "github.com/anibaldeboni/rapper/internal/config"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigProvider is a mock of ConfigProvider interface.
type MockConfigProvider struct {
	ctrl     *gomock.Controller
	recorder *MockConfigProviderMockRecorder
	isgomock struct{}
}

// MockConfigProviderMockRecorder is the mock recorder for MockConfigProvider.
type MockConfigProviderMockRecorder struct {
	mock *MockConfigProvider
}

// NewMockConfigProvider creates a new mock instance.
func NewMockConfigProvider(ctrl *gomock.Controller) *MockConfigProvider {
	mock := &MockConfigProvider{ctrl: ctrl}
	mock.recorder = &MockConfigProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigProvider) EXPECT() *MockConfigProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConfigProvider) Get() *config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*config.Config)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockConfigProviderMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigProvider)(nil).Get))
}

// OnChange mocks base method.
func (m *MockConfigProvider) OnChange(callback func(*config.Config)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnChange", callback)
}

// OnChange indicates an expected call of OnChange.
func (mr *MockConfigProviderMockRecorder) OnChange(callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChange", reflect.TypeOf((*MockConfigProvider)(nil).OnChange), callback)
}
