// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anibaldeboni/rapper/internal/ui/ports (interfaces: LogService)
//
// Generated by this command:
//
//	mockgen -destination ../mock/log_service_mock.go -package mock_ui github.com/anibaldeboni/rapper/internal/ui/ports LogService
//

// Package mock_ui is a generated GoMock package.
package mock_ui

import (
	reflect "reflect"

	logs "github.com/anibaldeboni/rapper/internal/logs"
	gomock "go.uber.org/mock/gomock"
)

// MockLogService is a mock of LogService interface.
type MockLogService struct {
	ctrl     *gomock.Controller
	recorder *MockLogServiceMockRecorder
	isgomock struct{}
}

// MockLogServiceMockRecorder is the mock recorder for MockLogService.
type MockLogServiceMockRecorder struct {
	mock *MockLogService
}

// NewMockLogService creates a new mock instance.
func NewMockLogService(ctrl *gomock.Controller) *MockLogService {
	mock := &MockLogService{ctrl: ctrl}
	mock.recorder = &MockLogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogService) EXPECT() *MockLogServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockLogService) Add(msg logs.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", msg)
}

// Add indicates an expected call of Add.
func (mr *MockLogServiceMockRecorder) Add(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockLogService)(nil).Add), msg)
}

// Get mocks base method.
func (m *MockLogService) Get() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockLogServiceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLogService)(nil).Get))
}
