// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anibaldeboni/rapper/internal/ui/ports (interfaces: LogProvider)
//
// Generated by this command:
//
//	mockgen -destination ../mock/log_provider_mock.go -package mock_ui github.com/anibaldeboni/rapper/internal/ui/ports LogProvider
//

// Package mock_ui is a generated GoMock package.
package mock_ui

import (
	reflect "reflect"

	logs "github.com/anibaldeboni/rapper/internal/logs"
	gomock "go.uber.org/mock/gomock"
)

// MockLogProvider is a mock of LogProvider interface.
type MockLogProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLogProviderMockRecorder
	isgomock struct{}
}

// MockLogProviderMockRecorder is the mock recorder for MockLogProvider.
type MockLogProviderMockRecorder struct {
	mock *MockLogProvider
}

// NewMockLogProvider creates a new mock instance.
func NewMockLogProvider(ctrl *gomock.Controller) *MockLogProvider {
	mock := &MockLogProvider{ctrl: ctrl}
	mock.recorder = &MockLogProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogProvider) EXPECT() *MockLogProviderMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockLogProvider) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear.
func (mr *MockLogProviderMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockLogProvider)(nil).Clear))
}

// Get mocks base method.
func (m *MockLogProvider) Get() []logs.LogMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]logs.LogMessage)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockLogProviderMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLogProvider)(nil).Get))
}
