// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anibaldeboni/rapper/internal/ui/ports (interfaces: ProcessorController)
//
// Generated by this command:
//
//	mockgen -destination ../mock/processor_controller_mock.go -package mock_ui github.com/anibaldeboni/rapper/internal/ui/ports ProcessorController
//

// Package mock_ui is a generated GoMock package.
package mock_ui

import (
	context "context"
	reflect "reflect"

	ports "github.com/anibaldeboni/rapper/internal/ui/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessorController is a mock of ProcessorController interface.
type MockProcessorController struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorControllerMockRecorder
	isgomock struct{}
}

// MockProcessorControllerMockRecorder is the mock recorder for MockProcessorController.
type MockProcessorControllerMockRecorder struct {
	mock *MockProcessorController
}

// NewMockProcessorController creates a new mock instance.
func NewMockProcessorController(ctrl *gomock.Controller) *MockProcessorController {
	mock := &MockProcessorController{ctrl: ctrl}
	mock.recorder = &MockProcessorControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessorController) EXPECT() *MockProcessorControllerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockProcessorController) Do(ctx context.Context, filePath string) (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, filePath)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockProcessorControllerMockRecorder) Do(ctx, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockProcessorController)(nil).Do), ctx, filePath)
}

// GetMetrics mocks base method.
func (m *MockProcessorController) GetMetrics() ports.ProcessorMetrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].(ports.ProcessorMetrics)
	return ret0
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockProcessorControllerMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockProcessorController)(nil).GetMetrics))
}

// GetWorkerCount mocks base method.
func (m *MockProcessorController) GetWorkerCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetWorkerCount indicates an expected call of GetWorkerCount.
func (mr *MockProcessorControllerMockRecorder) GetWorkerCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerCount", reflect.TypeOf((*MockProcessorController)(nil).GetWorkerCount))
}

// SetWorkers mocks base method.
func (m *MockProcessorController) SetWorkers(n int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetWorkers", n)
}

// SetWorkers indicates an expected call of SetWorkers.
func (mr *MockProcessorControllerMockRecorder) SetWorkers(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkers", reflect.TypeOf((*MockProcessorController)(nil).SetWorkers), n)
}
