// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anibaldeboni/rapper/internal/ui/ports (interfaces: RequestLogger)
//
// Generated by this command:
//
//	mockgen -destination ../mock/request_logger_mock.go -package mock_ui github.com/anibaldeboni/rapper/internal/ui/ports RequestLogger
//

// Package mock_ui is a generated GoMock package.
package mock_ui

import (
	reflect "reflect"

	logs "github.com/anibaldeboni/rapper/internal/logs"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestLogger is a mock of RequestLogger interface.
type MockRequestLogger struct {
	ctrl     *gomock.Controller
	recorder *MockRequestLoggerMockRecorder
	isgomock struct{}
}

// MockRequestLoggerMockRecorder is the mock recorder for MockRequestLogger.
type MockRequestLoggerMockRecorder struct {
	mock *MockRequestLogger
}

// NewMockRequestLogger creates a new mock instance.
func NewMockRequestLogger(ctrl *gomock.Controller) *MockRequestLogger {
	mock := &MockRequestLogger{ctrl: ctrl}
	mock.recorder = &MockRequestLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestLogger) EXPECT() *MockRequestLoggerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRequestLogger) Add(msg logs.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", msg)
}

// Add indicates an expected call of Add.
func (mr *MockRequestLoggerMockRecorder) Add(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRequestLogger)(nil).Add), msg)
}
