// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	web "github.com/anibaldeboni/rapper/internal/web"

	mock "github.com/stretchr/testify/mock"
)

// HttpGateway is an autogenerated mock type for the HttpGateway type
type HttpGateway struct {
	mock.Mock
}

// Exec provides a mock function with given fields: variables
func (_m *HttpGateway) Exec(variables map[string]string) (web.Response, error) {
	ret := _m.Called(variables)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 web.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]string) (web.Response, error)); ok {
		return rf(variables)
	}
	if rf, ok := ret.Get(0).(func(map[string]string) web.Response); ok {
		r0 = rf(variables)
	} else {
		r0 = ret.Get(0).(web.Response)
	}

	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(variables)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHttpGateway creates a new instance of HttpGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHttpGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *HttpGateway {
	mock := &HttpGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
