// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anibaldeboni/rapper/internal/processor (interfaces: Processor)
//
// Generated by this command:
//
//	mockgen -destination mock/processor_mock.go github.com/anibaldeboni/rapper/internal/processor Processor
//

// Package mock_processor is a generated GoMock package.
package mock_processor

import (
	context "context"
	reflect "reflect"

	processor "github.com/anibaldeboni/rapper/internal/processor"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessor is a mock of Processor interface.
type MockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorMockRecorder
	isgomock struct{}
}

// MockProcessorMockRecorder is the mock recorder for MockProcessor.
type MockProcessorMockRecorder struct {
	mock *MockProcessor
}

// NewMockProcessor creates a new mock instance.
func NewMockProcessor(ctrl *gomock.Controller) *MockProcessor {
	mock := &MockProcessor{ctrl: ctrl}
	mock.recorder = &MockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessor) EXPECT() *MockProcessorMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockProcessor) Do(ctx context.Context, filePath string) (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, filePath)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockProcessorMockRecorder) Do(ctx, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockProcessor)(nil).Do), ctx, filePath)
}

// GetMetrics mocks base method.
func (m *MockProcessor) GetMetrics() processor.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].(processor.Metrics)
	return ret0
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockProcessorMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockProcessor)(nil).GetMetrics))
}

// GetWorkerCount mocks base method.
func (m *MockProcessor) GetWorkerCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetWorkerCount indicates an expected call of GetWorkerCount.
func (mr *MockProcessorMockRecorder) GetWorkerCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerCount", reflect.TypeOf((*MockProcessor)(nil).GetWorkerCount))
}

// SetWorkers mocks base method.
func (m *MockProcessor) SetWorkers(n int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetWorkers", n)
}

// SetWorkers indicates an expected call of SetWorkers.
func (mr *MockProcessorMockRecorder) SetWorkers(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkers", reflect.TypeOf((*MockProcessor)(nil).SetWorkers), n)
}
