// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anibaldeboni/rapper/internal/web (interfaces: HttpClient)
//
// Generated by this command:
//
//	mockgen -destination mock/client_mock.go github.com/anibaldeboni/rapper/internal/web HttpClient
//

// Package mock_web is a generated GoMock package.
package mock_web

import (
	context "context"
	io "io"
	reflect "reflect"

	web "github.com/anibaldeboni/rapper/internal/web"
	gomock "go.uber.org/mock/gomock"
)

// MockHttpClient is a mock of HttpClient interface.
type MockHttpClient struct {
	ctrl     *gomock.Controller
	recorder *MockHttpClientMockRecorder
	isgomock struct{}
}

// MockHttpClientMockRecorder is the mock recorder for MockHttpClient.
type MockHttpClientMockRecorder struct {
	mock *MockHttpClient
}

// NewMockHttpClient creates a new mock instance.
func NewMockHttpClient(ctrl *gomock.Controller) *MockHttpClient {
	mock := &MockHttpClient{ctrl: ctrl}
	mock.recorder = &MockHttpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpClient) EXPECT() *MockHttpClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockHttpClient) Delete(ctx context.Context, url string, headers map[string]string) (web.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, url, headers)
	ret0, _ := ret[0].(web.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockHttpClientMockRecorder) Delete(ctx, url, headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHttpClient)(nil).Delete), ctx, url, headers)
}

// Get mocks base method.
func (m *MockHttpClient) Get(ctx context.Context, url string, headers map[string]string) (web.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, url, headers)
	ret0, _ := ret[0].(web.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHttpClientMockRecorder) Get(ctx, url, headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHttpClient)(nil).Get), ctx, url, headers)
}

// Patch mocks base method.
func (m *MockHttpClient) Patch(ctx context.Context, url string, body io.Reader, headers map[string]string) (web.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ctx, url, body, headers)
	ret0, _ := ret[0].(web.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockHttpClientMockRecorder) Patch(ctx, url, body, headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockHttpClient)(nil).Patch), ctx, url, body, headers)
}

// Post mocks base method.
func (m *MockHttpClient) Post(ctx context.Context, url string, body io.Reader, headers map[string]string) (web.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ctx, url, body, headers)
	ret0, _ := ret[0].(web.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockHttpClientMockRecorder) Post(ctx, url, body, headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockHttpClient)(nil).Post), ctx, url, body, headers)
}

// Put mocks base method.
func (m *MockHttpClient) Put(ctx context.Context, url string, body io.Reader, headers map[string]string) (web.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, url, body, headers)
	ret0, _ := ret[0].(web.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockHttpClientMockRecorder) Put(ctx, url, body, headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockHttpClient)(nil).Put), ctx, url, body, headers)
}
