name: Tests

on: workflow_call

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: false

      - name: Download dependencies
        run: go mod download -x

      - name: Run tests
        run: go run gotest.tools/gotestsum@latest --format pkgname -- -v -cover ./...
